### ISSUE TITLE
Spaces in file names break output

### ISSUE THREAD

**Issue by aleksejrs** [capncodewash/Misc-shell-scripts#1]
Only the part before the first space gets into the missing_files.txt.

**Comment by capncodewash** [comment]
Hi @aleksejrs - feel free to send a pull request for these changes.

**Comment by aleksejrs** [comment]
I will have to learn more about how redirection and awk work first.

**Comment by capncodewash** [comment]
okay, best of luck! :+1:

**Comment by aleksejrs** [comment]
Without having tried in the script itself, I think `awk '{print $2}'` (outputs only the second word) can be replaced with `cut --delimiter=' ' --fields=2-` (outputs everything starting with the second word).
