### ISSUE TITLE
Remove duplicates where necessary

### ISSUE THREAD

**Issue by aleksejrs** [capncodewash/Misc-shell-scripts#3]
If there are multiple copies of a file in a directory, output will contain sets of duplicates.  Adding “`|sort|uniq`” before the `>` fixes that.

**Comment by capncodewash** [comment]
Hi @aleksejrs - feel free to send a pull request for these changes.

**Comment by aleksejrs** [comment]
This change was intended for manual use.  Maybe it's bad for use with Vifm's custom view (but that's not really automated yet anyway).
